### ISSUE TITLE
Add readiness and liveness probes to the k8s deployment

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#6]
```
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
```
